# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate k Nearest Neighbors from Euclidean distance metric
#'
#' This function returns a logical vector identifying if
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An m x n numeric matrix
#' @param k The number of nearest neighbors to return
#' per sample
#' @return An m x k matrix of indicies 1...k of the
#' nearest neighbors for the specified row.
#' @export
calcKNNgraph <- function(x, k = 1L) {
    .Call('scTools_calcKNNgraph', PACKAGE = 'scTools', x, k)
}

