# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate k Nearest Neighbors from variable distance metric
#'
#' Each distance metric has its own function for speed/efficiency
#' This takes a sample X feature matrix and returns
#' a matrix of k nearest neighbors
#'
#' @param x An m x n numeric matrix
#' @param k The number of nearest neighbors to return
#' per sample
#' @return An m x k matrix of indicies 1...k of the
#' nearest neighbors for the specified row.
#' @export
calcKNNgraph_pearson <- function(x, k = 1L) {
    .Call('scTools_calcKNNgraph_pearson', PACKAGE = 'scTools', x, k)
}

#' @export
calcKNNgraph_euclidean <- function(x, k = 1L) {
    .Call('scTools_calcKNNgraph_euclidean', PACKAGE = 'scTools', x, k)
}

